# Generated by Django 3.1.7 on 2021-04-08 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='کاربر ویزه تا'),
        ),
    ]
